# Generated by Django 2.0 on 2018-08-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180805_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
