# Generated by Django 2.0 on 2018-08-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180805_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='department',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.Category'),
        ),
    ]
